name: push2d_lowdim

obs_dim: 20 # 9*2 keypoints + 2 state
action_dim: 2
keypoint_dim: 2

env_runner:
  _target_: diffusion_policy.env_runner.push2d_keypoints_runner_w_langtraj.Push2dKeypointsRunner
  keypoint_visible_rate: ${keypoint_visible_rate}
  n_train: 6
  n_train_vis: 6
  train_start_seed: 0
  n_test: 2
  n_test_vis: 2
  legacy_test: True
  test_start_seed: 100000
  max_steps: 100
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 10
  agent_keypoints: False
  past_action: ${past_action_visible}
  n_envs: null

dataset:
  _target_: diffusion_policy.dataset.push2d_finetune_dataset_langtraj_idx.Push2dLowdimDataset
  train_zarr_path: diffusion_policy/data/push2d/bimodal_50_push2d.zarr
  # train_zarr_path: diffusion_policy/data/push2d/one_ood_bimodal_push2d.zarr
  # target_zarr_path: diffusion_policy/data/push2d/target_single_push2d.zarr
  # target_zarr_path: diffusion_policy/data/push2d/target_ten_push2d.zarr
  target_zarr_path: diffusion_policy/data/push2d/comp_multiple_push2d.zarr
  # target_zarr_path: diffusion_policy/data/push2d/indist_target_single_push2d.zarr
  # target_zarr_path: diffusion_policy/data/push2d/circle_target_single_push2d.zarr
  # target_zarr_path: diffusion_policy/data/push2d/one_recovery_bimodal_push2d.zarr
  
  # zarr_path: diffusion_policy/data/push2d/small_bimodal_push2d.zarr
  # zarr_path: diffusion_policy/data/push2d/test_eachmode_push2d.zarr
  use_target: True
  utterance_input: ${eval:'None'}
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.00
  max_train_episodes: 90
